# Generated by Django 3.0.5 on 2020-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='correct_answer',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
